Refactor
cupitman9/budget-bot pull request #1
Opened 2024-01-15 17:19 UTC by cupitman9

2024-01-31 16:37 UTC, sula7 requested changes

2024-01-31 16:37 UTC, sula7 commented on cmd/main.go
> +	"github.com/jackc/pgx/v4/pgxpool"
Use [`github.com/jackc/pgx/v5`](https://github.com/jackc/pgx?tab=readme-ov-file#example-usage)

2024-01-31 16:37 UTC, sula7 commented on internal/bot/callback_handler.go
> +	"budget-bot/internal/model"
rename to `github.com/cupitman9/budget-bot`. At `go.mod` as well

2024-01-31 16:37 UTC, sula7 commented on internal/storage/storage.go
> +	_, err := s.db.Exec(context.Background(), query, user.Username, user.ChatID, user.Language, user.CreatedAt)
pass context here and use instead of `context.Background()`  
Do it for each method in this file

2024-01-31 16:37 UTC, sula7 commented on go.mod
> +module budget-bot
let's use go1.21 (see line 3)

2024-01-31 16:37 UTC, sula7 commented on cmd/main.go
> +		appLogger.Fatal("POSTGRES_DSN is not set")
let's use https://github.com/caarlos0/env. Check out usage examples

2024-01-31 16:37 UTC, sula7 commented on internal/bot/register.go
> +	"budget-bot/internal/storage"
line 11 is too long, remove `userSessions map[int64]*model.UserSession`

2024-01-31 16:37 UTC, sula7 commented on cmd/main.go
> +		log.Fatalf("error loading configuration: %v", err)
log messages should have the same structure. If you decided to start each message with `error ...` then apply this way to all other log messages over the project

2024-01-31 16:37 UTC, sula7 commented on internal/config/config.go
> +		BotToken:    os.Getenv("TELEGRAM_BOT_TOKEN"),
remove returning `error` at line 14 because it's always nil

2024-01-31 16:37 UTC, sula7 commented on internal/logger/logger.go
> +func New(logLevel string) *logrus.Logger {
`logLevel` is unused

2024-01-31 16:37 UTC, sula7 commented on internal/logger/logger.go
> +func New(logLevel string) *logrus.Logger {
remove var log at line 9

2024-03-11 17:46 UTC, cupitman9 commented on internal/storage/storage.go
> +	_, err := s.db.Exec(context.Background(), query, user.Username, user.ChatID, user.Language, user.CreatedAt)
impossible because calling func doesnt have context

2024-03-26 21:44 UTC, merged